# Adapted from https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/
---
name: 'Build'

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/unifi
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}
          IS_TAGGED=false

          # If this is git tag, use the tag name as a docker tag
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            IS_TAGGED=true
          fi
          TAGS="${IMAGE_NAME}:${VERSION},${IMAGE_NAME}:${SHORTREF}"

          # If the VERSION looks like a version number, assume that
          # this is the most recent version of the image and also
          # tag it 'latest'.
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${IMAGE_NAME}:latest"
          fi

          echo "IS_TAGGED=${IS_TAGGED} - IMAGE_NAME=${IMAGE_NAME} - TAGS=${TAGS}"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=image_name::${IMAGE_NAME}
          echo ::set-output name=is_tagged::${IS_TAGGED}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          install: true # set as default builder

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: ${{ steps.prep.outputs.is_tagged == 'true' }}
          tags: ${{ steps.prep.outputs.tags }}
